# Site settings
title: Putting It Together
header-img: img/home-bg.png
email: ericshiels2@gmail.com
copyright_name: E-Shiels
description: > # this means to ignore newlines until "baseurl:"
  My journey as I try to combine everything I know about programming.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  E-Shiels
learn_profile: E-Shiels
email_username: ericshiels2@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
